<?php
@include("../../inc/header.php");

/*
		SoftName : EmpireBak
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `lonking_enewsclasstemp`;");
E_C("CREATE TABLE `lonking_enewsclasstemp` (
  `tempid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `tempname` varchar(30) NOT NULL DEFAULT '',
  `temptext` mediumtext NOT NULL,
  `classid` smallint(5) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`tempid`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8");
E_D("replace into `lonking_enewsclasstemp` values('3','产品封面模板','<!DOCTYPE html>\r\n<html>\r\n<head>\r\n  <title>[!--pagetitle--]</title>\r\n  <meta name=\\\\\"keywords\\\\\" content=\\\\\"[!--pagekey--]\\\\\">\r\n  <meta name=\\\\\"description\\\\\" content=\\\\\"[!--pagedes--]\\\\\">\r\n  <meta name=\\\\\"viewport\\\\\" content=\\\\\"width=device-width,initial-scale=1.0\\\\\">\r\n  <meta http-equiv=\\\\\"content-type\\\\\" content=\\\\\"txt/html; charset=utf-8\\\\\" />\r\n  <link rel=\\\\\"shortcut icon\\\\\" href=\\\\\"/favicon.ico\\\\\" type=\\\\\"image/x-icon\\\\\" />\r\n  <link rel=\\\\\"stylesheet\\\\\" href=\\\\\"/skin/default/css/common.css\\\\\">\r\n  <link rel=\\\\\"stylesheet\\\\\" href=\\\\\"/skin/default/css/product.css\\\\\">\r\n</head>\r\n<body>\r\n  [!--temp.header--]\r\n  <!-- 静态banner -->\r\n  <div class=\\\\\"calm\\\\\">\r\n    <img src=\\\\\"../skin/default/images/calm.jpg\\\\\" alt=\\\\\"\\\\\">\r\n  </div>\r\n  <!-- 面包屑导航 -->\r\n  <div class=\\\\\"crumb\\\\\">\r\n    <div class=\\\\\"container\\\\\">\r\n      <div class=\\\\\"crumb-box\\\\\">\r\n          <span>您现在的位置：[!--newsnav--]\r\n      </div>\r\n    </div>\r\n  </div>\r\n  <!-- 内容 -->\r\n  <div class=\\\\\"product\\\\\">\r\n    <div class=\\\\\"container\\\\\">\r\n      <div class=\\\\\"main clear\\\\\">\r\n        <div class=\\\\\"main-left\\\\\">\r\n          <div class=\\\\\"main-title\\\\\">[!--class.name--]</div>\r\n          [!--temp.product_left--]\r\n        </div>\r\n        <div class=\\\\\"main-right\\\\\">\r\n          <ul class=\\\\\"list-right clear\\\\\">\r\n            [e:loop={\\\\\"select classid,classname,classimg,classpath from lonking_enewsclass where bclassid=21\\\\\",1,24,0}]\r\n            <li>\r\n              <a href=\\\\\"/<?=\$bqr[classpath]?>\\\\\">\r\n                <img src=\\\\\"<?=\$bqr[classimg]?>\\\\\" alt=\\\\\"<?=\$bqr[classname]?>\\\\\">\r\n                <p><?=\$bqr[classname]?></p>\r\n              </a>\r\n            </li>\r\n            [/e:loop]\r\n          </ul>\r\n        </div>\r\n      </div>\r\n    </div>\r\n  </div>\r\n  [!--temp.footer--]\r\n</body>\r\n</html>','0');");
E_D("replace into `lonking_enewsclasstemp` values('4','工程封面模板','<!DOCTYPE html>\r\n<html>\r\n<head>\r\n  <title>[!--pagetitle--]</title>\r\n  <meta name=\\\\\"keywords\\\\\" content=\\\\\"[!--pagekey--]\\\\\">\r\n  <meta name=\\\\\"description\\\\\" content=\\\\\"[!--pagedes--]\\\\\">\r\n  <meta name=\\\\\"viewport\\\\\" content=\\\\\"width=device-width,initial-scale=1.0\\\\\">\r\n  <meta http-equiv=\\\\\"content-type\\\\\" content=\\\\\"txt/html; charset=utf-8\\\\\" />\r\n  <link rel=\\\\\"shortcut icon\\\\\" href=\\\\\"/favicon.ico\\\\\" type=\\\\\"image/x-icon\\\\\" />\r\n  <link rel=\\\\\"stylesheet\\\\\" href=\\\\\"/skin/default/css/common.css\\\\\">\r\n  <link rel=\\\\\"stylesheet\\\\\" href=\\\\\"/skin/default/css/project.css\\\\\">\r\n</head>\r\n<body>\r\n  [!--temp.header--]\r\n  <!-- 静态banner -->\r\n  <div class=\\\\\"calm\\\\\">\r\n    <img src=\\\\\"../skin/default/images/calm.jpg\\\\\" alt=\\\\\"\\\\\">\r\n  </div>\r\n  <!-- 面包屑导航 -->\r\n  <div class=\\\\\"crumb\\\\\">\r\n    <div class=\\\\\"container\\\\\">\r\n      <div class=\\\\\"crumb-box\\\\\">\r\n          <span>您现在的位置：[!--newsnav--]\r\n      </div>\r\n    </div>\r\n  </div>\r\n  <!-- 内容 -->\r\n  <div class=\\\\\"product\\\\\">\r\n    <div class=\\\\\"container\\\\\">\r\n      <div class=\\\\\"project-sort\\\\\">\r\n        <p>工程案例</p>\r\n        <div class=\\\\\"sort-list clear\\\\\">\r\n          [e:loop={\\\\\"select classid,classname,classimg,classpath from lonking_enewsclass where bclassid=20\\\\\",1,24,0}]\r\n          <a href=\\\\\"/<?=\$bqr[classpath]?>\\\\\"><?=\$bqr[classname]?></a>\r\n          [/e:loop]\r\n        </div>\r\n      </div>\r\n      <div class=\\\\\"example clear\\\\\">\r\n        [e:loop={\\\\\"select classid,classname,classimg,classpath from lonking_enewsclass where bclassid=20\\\\\",1,24,0}]\r\n        <div class=\\\\\"example-box\\\\\">\r\n          <a href=\\\\\"/<?=\$bqr[classpath]?>\\\\\"><img src=\\\\\"<?=\$bqr[classimg]?>\\\\\" alt=\\\\\"<?=\$bqr[classname]?>\\\\\"></a>\r\n          <h4><?=\$bqr[classname]?></h4>\r\n        </div>\r\n        [/e:loop]\r\n      </div>\r\n    </div>\r\n  </div>\r\n  [!--temp.footer--]\r\n</body>\r\n</html>','0');");
E_D("replace into `lonking_enewsclasstemp` values('5','新闻封面模板','<!DOCTYPE html>\r\n<html>\r\n<head>\r\n  <title>[!--pagetitle--]</title>\r\n  <meta name=\\\\\"keywords\\\\\" content=\\\\\"[!--pagekey--]\\\\\">\r\n  <meta name=\\\\\"description\\\\\" content=\\\\\"[!--pagedes--]\\\\\">\r\n  <meta name=\\\\\"viewport\\\\\" content=\\\\\"width=device-width,initial-scale=1.0\\\\\">\r\n  <meta http-equiv=\\\\\"content-type\\\\\" content=\\\\\"txt/html; charset=utf-8\\\\\" />\r\n  <link rel=\\\\\"shortcut icon\\\\\" href=\\\\\"/favicon.ico\\\\\" type=\\\\\"image/x-icon\\\\\" />\r\n  <link rel=\\\\\"stylesheet\\\\\" href=\\\\\"/skin/default/css/common.css\\\\\">\r\n  <link rel=\\\\\"stylesheet\\\\\" href=\\\\\"/skin/default/css/news.css\\\\\">\r\n</head>\r\n<body>\r\n  [!--temp.header--]\r\n  <!-- 静态banner -->\r\n  <div class=\\\\\"calm\\\\\">\r\n    <img src=\\\\\"../skin/default/images/calm.jpg\\\\\" alt=\\\\\"\\\\\">\r\n  </div>\r\n  <!-- 面包屑导航 -->\r\n  <div class=\\\\\"crumb\\\\\">\r\n    <div class=\\\\\"container\\\\\">\r\n      <div class=\\\\\"crumb-box\\\\\">\r\n          <span>您现在的位置：[!--newsnav--]\r\n      </div>\r\n    </div>\r\n  </div>\r\n  <!-- 内容 -->\r\n  <div class=\\\\\"product\\\\\">\r\n    <div class=\\\\\"container\\\\\">\r\n      <div class=\\\\\"main clear\\\\\">\r\n        <div class=\\\\\"main-left\\\\\">\r\n          <div class=\\\\\"main-title\\\\\">[!--class.name--]</div>\r\n          [!--temp.news_left--]\r\n        </div>\r\n        <div class=\\\\\"main-right\\\\\">\r\n          <div class=\\\\\"news-list\\\\\">\r\n            [e:loop={22,10,0,0,\\\\''\\\\'',\\\\''newstime DESC\\\\''}]\r\n            <div class=\\\\\"news-box\\\\\">\r\n              <a href=\\\\\"<?=\$bqsr[\\\\''titleurl\\\\'']?>\\\\\" class=\\\\\"news-title\\\\\" target=\\\\\"_blank\\\\\"><?=\$bqr[\\\\''title\\\\'']?></a>\r\n              <p class=\\\\\"news-desc\\\\\"><?=\$bqr[\\\\''intro\\\\'']?></p>\r\n              <a href=\\\\\"<?=\$bqsr[\\\\''titleurl\\\\'']?>\\\\\" class=\\\\\"news-more\\\\\" target=\\\\\"_blank\\\\\">&nbsp;>>&nbsp;查看详情</a>\r\n              <span class=\\\\\"news-time\\\\\"><?=date(\\\\''Y-m-d\\\\'',\$bqr[newstime])?></span>\r\n            </div>\r\n            [/e:loop]\r\n          </div>\r\n        </div>\r\n      </div>\r\n    </div>\r\n  </div>\r\n  [!--temp.footer--]\r\n</body>\r\n</html>','0');");

@include("../../inc/footer.php");
?>